name: vtsmobileapp
description: "VTS Mobile app."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.9
  image_picker: ^0.8.7+4
  image_picker_web: ^2.0.0
  intl: ^0.18.0
  dio: ^5.1.1
  http_parser: ^4.0.2  # Downgraded version for compatibility
  pdf: ^3.6.0
  printing: ^5.5.0
  path_provider: ^2.0.11
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.12.0 # Use the latest version available
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA-Regular.ttf
        - asset: assets/fonts/EuclidCircularA-Bold.ttf
          weight: 700
        - asset: assets/fonts/EuclidCircularA-Italic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  web: true  # Support for web
  windows:
    generate: true  # Enable for Windows
  macos:
    generate: true  # Enable for macOS
  image_path: "assets/images/logo.png"  # Path to your logo.png
  remove_alpha_ios: true  # Remove alpha channel for iOS
